//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotFinder.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpotFinder.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquiring location.
        /// </summary>
        internal static string AcquiringLocationLabel {
            get {
                return ResourceManager.GetString("AcquiringLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Każdy spot powinien mieć tytuł, typ oraz opis. W celu jak najlepszego późniejszego wyszukiwania zaznacz przeszkody, które znajdują się w dodawanym miejscu. Pierwsze zdjęcie powinno być możliwie jak najlepsze ponieważ jest zdjęciem głównym. Po kliknięciu na zdjęcie można je usunąć. Powodzenia!.
        /// </summary>
        internal static string AddingInformation {
            get {
                return ResourceManager.GetString("AddingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photo.
        /// </summary>
        internal static string AddPhotoButton {
            get {
                return ResourceManager.GetString("AddPhotoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add place.
        /// </summary>
        internal static string AddPlacePageTitle {
            get {
                return ResourceManager.GetString("AddPlacePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddSpotButton {
            get {
                return ResourceManager.GetString("AddSpotButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string AlertNo {
            get {
                return ResourceManager.GetString("AlertNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want remove this photo?.
        /// </summary>
        internal static string AlertRemovePhoto {
            get {
                return ResourceManager.GetString("AlertRemovePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string AlertTitle {
            get {
                return ResourceManager.GetString("AlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string AlertYes {
            get {
                return ResourceManager.GetString("AlertYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app contains all skateboarding spots and skateparks in one application..
        /// </summary>
        internal static string AppDescriptionLabel {
            get {
                return ResourceManager.GetString("AppDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want cancell this report?.
        /// </summary>
        internal static string CancelReportAlert {
            get {
                return ResourceManager.GetString("CancelReportAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string CityPlaceholder {
            get {
                return ResourceManager.GetString("CityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found .
        /// </summary>
        internal static string CountSpotsInformationFoundPartOne {
            get {
                return ResourceManager.GetString("CountSpotsInformationFoundPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  places..
        /// </summary>
        internal static string CountSpotsInformationFoundPartTwo {
            get {
                return ResourceManager.GetString("CountSpotsInformationFoundPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found places matches provided criteria..
        /// </summary>
        internal static string CountSpotsInformationNotFound {
            get {
                return ResourceManager.GetString("CountSpotsInformationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine search distance: .
        /// </summary>
        internal static string CriteriaDistanceLabel {
            get {
                return ResourceManager.GetString("CriteriaDistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("DescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string FilterLabel {
            get {
                return ResourceManager.GetString("FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine global search distance: .
        /// </summary>
        internal static string GlobalDistanceSettingsLabel {
            get {
                return ResourceManager.GetString("GlobalDistanceSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string GoBackCommandTitle {
            get {
                return ResourceManager.GetString("GoBackCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string ListPageTitle {
            get {
                return ResourceManager.GetString("ListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localize.
        /// </summary>
        internal static string LocateCommandTitle {
            get {
                return ResourceManager.GetString("LocateCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use map to locate.
        /// </summary>
        internal static string LocateOnMapPageTitle {
            get {
                return ResourceManager.GetString("LocateOnMapPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your main city:.
        /// </summary>
        internal static string MainCityInfo {
            get {
                return ResourceManager.GetString("MainCityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city.
        /// </summary>
        internal static string MainCityPlaceholder {
            get {
                return ResourceManager.GetString("MainCityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search spots near to you.
        /// </summary>
        internal static string MainPageButtonText {
            get {
                return ResourceManager.GetString("MainPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string MapPageTitle {
            get {
                return ResourceManager.GetString("MapPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextCommandTitle {
            get {
                return ResourceManager.GetString("NextCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obstacles:.
        /// </summary>
        internal static string ObstaclesLabel {
            get {
                return ResourceManager.GetString("ObstaclesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string PlaceDetailsTitle {
            get {
                return ResourceManager.GetString("PlaceDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveSettingsButton {
            get {
                return ResourceManager.GetString("SaveSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine search distance: .
        /// </summary>
        internal static string SearchDistanceLabel {
            get {
                return ResourceManager.GetString("SearchDistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchPageTitle {
            get {
                return ResourceManager.GetString("SearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string SelectAllCommand {
            get {
                return ResourceManager.GetString("SelectAllCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot type.
        /// </summary>
        internal static string SpotTypePlaceholder {
            get {
                return ResourceManager.GetString("SpotTypePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        internal static string UploadingPrompt {
            get {
                return ResourceManager.GetString("UploadingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use device location.
        /// </summary>
        internal static string UseDeviceLocationLabel {
            get {
                return ResourceManager.GetString("UseDeviceLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use map for better locate:.
        /// </summary>
        internal static string UseMapLabel {
            get {
                return ResourceManager.GetString("UseMapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From where you want search?.
        /// </summary>
        internal static string WhereSearchLabel {
            get {
                return ResourceManager.GetString("WhereSearchLabel", resourceCulture);
            }
        }
    }
}
